"""Assemble the technical validation report.

Everything in `docs/validation/report.md` is generated by running the engine
against data it has never been tuned on, and every number in it is reproducible
by re-running this module. Nothing is typed in by hand.

The report deliberately states coverage next to accuracy, and states failures
rather than omitting them, because a validation chapter that only reports the
flattering half of a measurement is not a validation chapter.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import numpy as np

from cardiosignal import __version__, config
from cardiosignal.validation import ludb_eval, qtdb_eval, roundtrip


def synthetic_section() -> str:
    """Known-answer test: simulate at a set rate, measure it back."""
    import neurokit2 as nk

    from cardiosignal.detect.pan_tompkins import detect_single_lead

    rows = []
    for target in (45, 60, 75, 90, 120, 150):
        signal = nk.ecg_simulate(
            duration=10, sampling_rate=config.FS, heart_rate=target, random_state=7
        )
        detection = detect_single_lead(signal, config.FS)
        rr = detection.rr_intervals_ms()
        measured = 60000.0 / float(np.mean(rr)) if rr.size else float("nan")
        rows.append((target, detection.n_beats, measured, measured - target))

    lines = [
        "### Known-answer test (synthetic)",
        "",
        "| set rate (bpm) | beats found | measured (bpm) | error (bpm) |",
        "|---:|---:|---:|---:|",
    ]
    lines += [f"| {t} | {n} | {m:.1f} | {e:+.1f} |" for t, n, m, e in rows]
    lines += [
        "",
        "Simulated with `neurokit2.ecg_simulate`. This checks the arithmetic end to "
        "end against a known truth; it is not evidence about real ECGs, which is what "
        "the LUDB and QTDB sections are for.",
    ]
    return "\n".join(lines)


def roundtrip_section(out_dir: Path) -> str:
    import neurokit2 as nk

    from cardiosignal.detect.pan_tompkins import detect_r_peaks
    from cardiosignal.render.sheet import render_clean
    from cardiosignal.types import Recording

    base = nk.ecg_simulate(duration=10, sampling_rate=config.FS, heart_rate=72, random_state=11)
    gains = np.array([0.9, 1.2, 0.35, -1.05, 0.5, 0.85, -0.55, 0.75, 1.15, 1.35, 1.05, 0.7])
    signal = base[:, None] * gains[None, :]
    recording = Recording(ecg_id=900001, source="synthetic", signal=signal)

    image_path = out_dir / "roundtrip_sheet.png"
    render_clean(recording, image_path)

    detection = detect_r_peaks(signal, config.FS)
    rhythm_index = recording.leads.index(config.RHYTHM_LEAD)
    report = roundtrip.evaluate(
        image_path, signal[:, rhythm_index], detection.r_peaks, config.FS
    )
    return roundtrip.format_report(report)


def build(
    out_dir: Path | None = None,
    ludb_limit: int | None = None,
    qtdb_limit: int | None = None,
    progress: bool = True,
) -> Path:
    """Run every validation and write the report."""
    out_dir = out_dir or (config.DOCS_ROOT / "validation")
    out_dir.mkdir(parents=True, exist_ok=True)

    sections: list[str] = [
        "# CardioSaarthi — Layer 1 technical validation",
        "",
        f"Engine version `{__version__}`, schema `{config.SCHEMA_VERSION}`, "
        f"generated {datetime.now(UTC):%Y-%m-%d %H:%M UTC}.",
        "",
        "Regenerate with `cardiosignal validate --report`. Every figure below is "
        "computed, not transcribed.",
        "",
        "All measurement is deterministic signal processing. No model is consulted "
        "anywhere in the pipeline these numbers describe.",
        "",
        "---",
        "",
    ]

    sections.append(synthetic_section())
    sections.append("\n---\n")

    print("Rendering and re-measuring the sheet...")
    sections.append(roundtrip_section(out_dir))
    sections.append("\n---\n")

    if ludb_eval.ludb.is_available():
        print("Evaluating against LUDB...")
        report = ludb_eval.evaluate(limit=ludb_limit, progress=progress)
        sections.append(ludb_eval.format_report(report))
    else:
        sections.append(
            "### Beat detection and delineation (LUDB)\n\n"
            "_LUDB not downloaded. Run `python scripts/download_data.py ludb`._"
        )
    sections.append("\n---\n")

    if qtdb_eval.qtdb.is_available():
        print("Evaluating against QTDB...")
        report = qtdb_eval.evaluate(limit=qtdb_limit, progress=progress)
        sections.append(qtdb_eval.format_report(report))
    else:
        sections.append(
            "### QT interval (QTDB)\n\n"
            "_QTDB not downloaded. Run `python scripts/download_data.py qtdb`._"
        )

    sections += [
        "\n---\n",
        "## Reading these numbers",
        "",
        "**Bias versus scatter.** A large bias is a systematic offset and is usually "
        "fixable in the algorithm; a large error with near-zero bias is scatter and is "
        "not. The two are reported separately for that reason.",
        "",
        "**Coverage is not optional.** A delineator that declines to place a boundary "
        "scores no error at all, so accuracy quoted without coverage is meaningless. "
        "Boundaries the engine refused to produce are counted as missing coverage and "
        "never averaged in as zero error.",
        "",
        "**P waves are the weak point, by design of the problem.** They are low "
        "amplitude, sometimes buried in the preceding T wave, and sometimes genuinely "
        "absent. The engine reports `P_ABSENT` rather than guessing, because an invented "
        "P wave yields a confident wrong PR interval and the platform would then mark a "
        "correct student answer wrong.",
        "",
        "**The confidence gate.** Cases below the confidence threshold are withheld from "
        "the student bank until a faculty reviewer confirms or corrects them. A case sent "
        "for review costs a reviewer two minutes; a bad measurement served to a student "
        "costs their trust in the platform.",
        "",
        "## Still to do",
        "",
        "- Physical check: print `calibration_sheet.pdf` at 100% scale and confirm with an "
        "ECG caliper that 200 ms measures exactly 5 mm.",
        "- Measurement agreement against faculty corrections, once the review queue has "
        "run (week 4+).",
    ]

    path = out_dir / "report.md"
    path.write_text("\n".join(sections) + "\n", encoding="utf-8")
    return path


__all__ = ["build", "roundtrip_section", "synthetic_section"]
